// <auto-generated />
namespace CapstoneProject.EvaluationMigrations.EvaluationContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EvaluationInitialSeed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EvaluationInitialSeed));
        
        string IMigrationMetadata.Id
        {
            get { return "201702151709071_Evaluation Initial Seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
